languageCode = "en"
languageName = "English"
weight = 1
title = "Yann Lemos"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
description = ""
logo = "C:\\Users\\yannd\\Downloads\\profilepic.png"

[params.author]
name = "Yann Lemos"
bio = "Game Developer"
image = "img/avatar.png"
links = [{ youtube = "https://www.youtube.com/@yannlemos"}, { instagram = "https://www.instagram.com/yann.lemos/"}, { github = "https://github.com/yannlemos" }, { linkedin = "https://www.linkedin.com/in/yannlemos/" }, {bluesky = "https://bsky.app/profile/yann-lemos.bsky.social"}, { email = "mailto:yannlemos@proton.me" }]
headline = "Opa, tudo bom?<br>I'm a game developer based in Rio de Janeiro, Brazil."

