colorScheme = "avocado"
defaultAppearance = "dark"
defaultBackgroundImage = "/img/background.svg"
autoSwitchAppearance = false
enableSearch = false
enableCodeCopy = false
disableImageOptimization = false
disableTextInHeader = false
smartTOC = true
highlightCurrentMenuArea = true
mainSections = [ "Project" ]

[header]
layout = "fixed-fill-blur"

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = false
showScrollToTop = true

[homepage]
layout = "background"
showRecent = true
showRecentItems = "3"
showMoreLink = true
showMoreLinkDest = "/projects"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = false
homepageImage = "/img/background.svg"

[article]
showDate = false
showViews = false
showLikes = false
showDateOnlyInArticle = false
showDateUpdated = false
showAuthor = false
showHero = true
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = true
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = false
showTableOfContents = true
showTaxonomies = true
showAuthorsBadges = false
showWordCount = false
showZenMode = false
heroStyle = "background"

[list]
showHero = true
heroStyle = "background"
layoutBackgroundBlur = true
layoutBackgroundHeaderSpace = false
showBreadcrumbs = false
showSummary = true
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
orderByWeight = true
groupByYear = false
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = true

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[buymeacoffee]

[verification]
